services:
  health-blog-platform:
    build: .
    image: health-blog-platform:latest
    container_name: health-blog-platform
    ports:
      - "8081:8081"
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/health_blog_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa

      SECURITY_JWT_SECRET: change-this-secret-to-a-long-random-production-value-32-bytes

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${MAIL_USERNAME:-ornsunlang75802gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-eupz hjil aqvw lpgl}
      MAIL_FROM: ornsunlang7580gmail.com
      APP_FRONTEND_URL: http://localhost:5173

    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - health-blog-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: health_blog_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - health-blog-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - health-blog-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - health-blog-net

volumes:
  health-blog-mysql-data:

networks:
  health-blog-net:
    driver: bridge